apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-auth
  labels:
    app.kubernetes.io/name: rabbitmq
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ .Values.auth.username | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.auth.password | quote }}

