apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app.kubernetes.io/name: rabbitmq
spec:
  selector:
    app.kubernetes.io/name: rabbitmq
  ports:
    - name: amqp
      port: {{ .Values.service.amqpPort }}
      targetPort: amqp
    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: management
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics

