apiVersion: v1
kind: ConfigMap
metadata:
  name: valkey-config
  labels:
    app.kubernetes.io/name: valkey
data:
  valkey.conf: |
    bind 0.0.0.0
    port 6379
    protected-mode no
    appendonly yes
    save 60 1000

