apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app.kubernetes.io/name: valkey
spec:
  selector:
    app.kubernetes.io/name: valkey
  ports:
    - name: valkey
      port: {{ .Values.service.port }}
      targetPort: valkey
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics

