apiVersion: v1
kind: Secret
metadata:
  name: worker-secrets
  labels:
    app.kubernetes.io/name: worker
    app.kubernetes.io/component: worker
type: Opaque
stringData:
  RABBITMQ_USERNAME: {{ .Values.secrets.rabbitmqUsername | quote }}
  RABBITMQ_PASSWORD: {{ .Values.secrets.rabbitmqPassword | quote }}
  VALKEY_PASSWORD: {{ .Values.secrets.valkeyPassword | quote }}

