apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: api
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  RABBITMQ_USERNAME: {{ .Values.secrets.rabbitmqUsername | quote }}
  RABBITMQ_PASSWORD: {{ .Values.secrets.rabbitmqPassword | quote }}
  VALKEY_PASSWORD: {{ .Values.secrets.valkeyPassword | quote }}

