{{- if and .Values.serviceMonitor.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api
  labels:
{{ toYaml .Values.serviceMonitor.labels | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/component: api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
